Cursor
tkalejandro/portfolio-sonia-coronado pull request #156
Opened 2024-04-07 17:10 UTC by Hicham2012

2024-04-18 06:33 UTC, tkalejandro requested changes
Some comments and you are good for best practices :D

2024-04-18 06:33 UTC, tkalejandro commented on .vscode/settings.json
> +    ]
Im just curious what does this do???

2024-04-18 06:33 UTC, tkalejandro commented on src/modules/Experience/Experience.tsx
> +import { CursorManage } from './components/Cursor/CursorManager';
Is there a way to avoid this duplicated import line, you already have access to Components in line 16.

Maybe create an index file in Cursor?   and `import * as Cursor from blabla` `Import * as CursorManager from blabla`

Note: YOu need to use `export const` instead of `export default` 

Later in the components Index you should import Cursor.

2024-04-18 06:33 UTC, tkalejandro commented on src/modules/Experience/components/Cursor/Cursor.tsx
> +  let divide = 3
If doesnt change, then is a CONST not a LET. 

Good practice, is too always take static information out of the React Render.... this way it doesnt need to render again...  (this way u keep whatever app u r doing, more efficient).   Is dumb for this case! but very useful tip!

2024-04-18 06:33 UTC, tkalejandro commented on src/modules/Experience/components/Cursor/cursor.css
> +} */
Do y ou need this?

2024-04-18 06:33 UTC, tkalejandro commented on src/modules/Experience/components/EnhancedGroup/EnhancedGroup.tsx
>      >
This is a very agressive move, becuase you are changing the style for everything where this is been use. Is this your goal? and it was intended. If is not, and is only a use case, maybe enhance the component and extended a property for example: 'defaultCursorStyle' and when is false, the style should not be apply. By default should be true.

2024-04-18 06:33 UTC, tkalejandro commented on src/modules/Experience/components/ThreeDButton/ThreeDButton.tsx
> +      // onPointerDown={() => changeHover(true)}
????

2024-04-18 06:33 UTC, tkalejandro commented on src/modules/Experience/scenes/AudioLibraryScene/AudioLibraryScene.tsx
> +    // document.body.style.cursor = 'default';
is this inteended?

2024-04-18 06:33 UTC, tkalejandro commented on src/modules/Experience/scenes/AudioLibraryScene/AudioLibraryScene.tsx
> +        // onPointerEnter={handlePointerEnter}
Same, if yes remove.

2024-04-18 06:33 UTC, tkalejandro commented on src/modules/Experience/components/Cursor/cursor.css
> +}
If you wanna use CSS....  Is it possible to create inline stlying, using the Box property sx .  And then target inside.

If is not the case, and you want to use CSS. Please use Modular CSS, is a cool feature from NextJS which allow you to write SAFE css files.    at the end your file should be call somethign like `cursor.module.css` Please check the NextJS documentation to make it work.

2024-04-18 06:33 UTC, tkalejandro commented on src/modules/Experience/scenes/ContactScene/ContactScene.tsx
> +  const resumeRef = useRef()
If you hover on those elements, you can tell what TS type it is. Avoid using Ts-ignore--- is very bad practice.

2024-04-18 06:33 UTC, tkalejandro commented on src/modules/Experience/scenes/ContactScene/ContactScene.tsx
> +                // @ts-ignore
remove :D

2024-04-18 06:33 UTC, tkalejandro commented on src/modules/Experience/scenes/ContactScene/ContactScene.tsx
> +                // @ts-ignore
remove :D

2024-04-18 06:33 UTC, tkalejandro commented on src/modules/Experience/scenes/ContactScene/ContactScene.tsx
> +                  // @ts-ignore
Remove :D.

2024-04-18 06:33 UTC, tkalejandro commented on src/modules/Experience/scenes/ContactScene/ContactScene.tsx
> +                  // @ts-ignore
Same :D

2024-04-18 06:33 UTC, tkalejandro commented on src/modules/Experience/scenes/ContactScene/ContactScene.tsx
> +                  // @ts-ignore
Here

2024-04-18 06:33 UTC, tkalejandro commented on src/modules/Experience/scenes/ContactScene/ContactScene.tsx
> +                  // @ts-ignore
And here :D

2024-04-18 06:33 UTC, tkalejandro commented on src/modules/Experience/scenes/ContactScene/ContactScene.tsx
> +                // @ts-ignore
Also Here

2024-04-18 06:33 UTC, tkalejandro commented on src/modules/Experience/scenes/ContactScene/ContactScene.tsx
> +                // @ts-ignore
And there

2024-04-18 06:33 UTC, tkalejandro commented on src/modules/Experience/scenes/MediaCoverageScene/components/MediaCard/MediaCard.tsx
> +  }
All this can be 1 function, that receives 1 parameter and depending the parameter u have different configurations.

2024-04-18 06:33 UTC, tkalejandro commented on src/modules/Experience/scenes/MediaCoverageScene/components/MediaCard/MediaCard.tsx
> +            onPointerOut={() => notHoverCard()}
you will call that function and set is true or false.

2024-04-18 06:33 UTC, tkalejandro commented on src/modules/Experience/scenes/ProjectsAwardsScene/components/Gallery/components/SecretButton/SecretButton.tsx
> +    // document.body.style.cursor = "none"
Do we need this comments?

2024-04-18 06:33 UTC, tkalejandro commented on src/modules/Experience/shaders/cursorShader/fragment.glsl
> +    // gl_FragColor = vec4(0.6, 0.3, 0.2, smoke);
do we need this comments?

2024-04-18 06:33 UTC, tkalejandro commented on src/modules/Experience/shaders/cursorShader/vertex.glsl
> +        // vec2(0.5, uv.y * 0.2 - 23.0 * 0.005)
Do we need this comemnts?

2024-04-18 06:33 UTC, tkalejandro commented on src/modules/Experience/shaders/cursorShader/vertex.glsl
> +    // gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
Do we need this comment?

2024-04-18 13:32 UTC, Hicham2012 commented on .vscode/settings.json
> +    ]
I am using a extension to check words spelling and corrcet them.
This object is used to ignore these specific words.

2024-04-18 13:44 UTC, Hicham2012 commented on src/modules/Experience/scenes/AudioLibraryScene/AudioLibraryScene.tsx
> +    // document.body.style.cursor = 'default';
Yes

2024-04-18 13:46 UTC, Hicham2012 commented on src/modules/Experience/components/EnhancedGroup/EnhancedGroup.tsx
>      >
Yes, my goal is to reset how the crsor behavior in the whole website and have full controle when customizing it.

2024-04-18 16:02 UTC, tkalejandro requested changes

2024-04-18 16:02 UTC, tkalejandro commented on src/modules/Experience/components/Cursor/Cursor.tsx
> +// import '@/theme/globals.css';
:D ?? ?

2024-04-18 16:02 UTC, tkalejandro commented on src/modules/Experience/components/Cursor/Cursor.tsx
> +  const divide = 3
Out of the React component, this means it should be out of. const Cursor  = () => {
}

after the imports

2024-04-18 16:02 UTC, tkalejandro commented on src/modules/Experience/components/Cursor/CursorManager.tsx
> +const CursorContext = createContext<any>(null);
You could type safe this, check the SoundManager context.

2024-04-18 16:02 UTC, tkalejandro commented on src/modules/Experience/components/Cursor/CursorManager.tsx
> +export const CursorManage = ({ children }: any) => {
It can be type safe. Check SoundManagerContext

2024-04-18 16:02 UTC, tkalejandro commented on src/modules/Experience/components/Cursor/CursorManager.tsx
> +  const [settings, setSettings] = useState<object>({
Object is another type as ANY ... FYI another type to avoid is Function.

This types doesnt provide safety.

You could create a new Type in the file. Is totally okay.

2024-04-18 16:02 UTC, tkalejandro commented on src/modules/Experience/components/Cursor/CursorManager.tsx
> +    // document.body.style.cursor = 'none';
need this?

2024-04-18 16:02 UTC, tkalejandro commented on src/modules/Experience/components/EnhancedGroup/EnhancedGroup.tsx
> +        // document.body.style.cursor = 'default !important';
This still an agressive solution. the pointer is lost in the elements that it needs to be a pointer.  I just double check on the preview.  Create a if else condition for when you dont need a pointer.

2024-04-19 06:55 UTC, tkalejandro requested changes
Some more comments

2024-04-19 06:55 UTC, tkalejandro commented on src/modules/Experience/components/Cursor/Cursor.tsx
> +  const insideRef = useRef<THREE.Mesh | any>()
Would you remember ewhat does ref and insideRef are in 1 year? XD maybe be a better name, is there a reason they still use ANY?  We can solve this together maybe today?

2024-04-19 06:55 UTC, tkalejandro commented on src/modules/Experience/scenes/MediaCoverageScene/components/MediaCard/MediaCard.tsx
> +  // }
Can be deleted?

2024-04-21 16:11 UTC, tkalejandro approved these changes

2024-04-21 16:11 UTC, merged